
#CREATE CUSTOMERS

CREATE TABLE CUSTOMERS (
    ID BIGINT NOT NULL,
    DOCUMENT_TYPE VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    BANK_ACCOUNT VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    ZIP_CODE VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(100) NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);

#CREATE RESTAURANTS

CREATE TABLE RESTAURANTS (
    ID BIGINT NOT NULL,
    CUSTOMERS_ID BIGINT NOT NULL,
    NIF VARCHAR(100) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    ZIP_CODE VARCHAR(100) NOT NULL,
    TAX_TYPE VARCHAR(10) NOT NULL,
    TAX_PERCENT DECIMAL(4,2) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    BANK_ACCOUNT VARCHAR(255) NOT NULL,
    MONETIZATION_TYPE VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (CUSTOMERS_ID) REFERENCES CUSTOMERS(ID)
);


#CREATE MENUS

CREATE TABLE MENUS (
    ID BIGINT NOT NULL,
    RESTAURANTS_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (RESTAURANTS_ID) REFERENCES RESTAURANTS(ID)
);

#CREATE CATEGORIES

CREATE TABLE CATEGORIES (
    ID BIGINT NOT NULL,
    MENUS_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (MENUS_ID) REFERENCES MENUS(ID)
);

#CREATE ITEMS

CREATE TABLE ITEMS (
    ID BIGINT NOT NULL,
    CATEGORIES_ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(6,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (CATEGORIES_ID) REFERENCES CATEGORIES(ID)
);

#CREATE TABLES

CREATE TABLE TABLES (
    ID BIGINT NOT NULL,
    RESTAURANTS_ID BIGINT NOT NULL,
    QR_CODE VARCHAR(255) NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (RESTAURANTS_ID) REFERENCES RESTAURANTS(ID)
);

#CREATE ORDERS

CREATE TABLE ORDERS (
    ID BIGINT NOT NULL,
    TABLES_ID BIGINT NOT NULL,
    SUBTOTAL VARCHAR(255) NOT NULL,
    TAX_PERCENT DECIMAL(4,2) NOT NULL,
    TAX_AMOUNT DECIMAL(9,2) NOT NULL,
    TOTAL DECIMAL(9,2) NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (TABLES_ID) REFERENCES TABLES(ID)
);

#CREATE ORDER_LINES

CREATE TABLE ORDER_LINES (
    ID BIGINT NOT NULL,
    ORDERS_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    LINE_TOTAL DECIMAL(9,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS(ID)
);

#MONTLY_REPORTS

CREATE TABLE MONTHLY_REPORTS (
    ID BIGINT NOT NULL,
    RESTAURANTS_ID BIGINT NOT NULL,
    TOTAL_ORDERS BIGINT NOT NULL,
    TOTAL_PROFIT DECIMAL(9,2) NOT NULL,
    TOTAL_COMISSIONS DECIMAL(9,2) NOT NULL,
    NET_PROFIT DECIMAL(9,2) NOT NULL,
    MONTH INT NOT NULL,
    YEAR INT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (RESTAURANTS_ID) REFERENCES RESTAURANTS(ID)
);

-- ROLLBACK DROP TABLE MONTHLY_REPORTS;
-- ROLLBACK DROP TABLE ORDER_LINES;
-- ROLLBACK DROP TABLE ORDERS;
-- ROLLBACK DROP TABLE TABLES;
-- ROLLBACK DROP TABLE ITEMS;
-- ROLLBACK DROP TABLE CATEGORIES;
-- ROLLBACK DROP TABLE MENUS;
-- ROLLBACK DROP TABLE RESTAURANTS;
-- ROLLBACK DROP TABLE CUSTOMERS;






